### ISSUE TITLE
Multiline comments not stripped when having trailing spaces

### ISSUE THREAD

**Issue by mrchandoo** [kkemple/grunt-stripcomments#14]
try stripping the below comments

  //this will be removed
var v="sss"; //this will not be removed
        /*
        * This comment is not removed.
        */

            /**
            *This will be removed.
            */
sdasd
 /*
 ** will not remove
 */

the plugin is so unpredictable, could you please debug and check ?

**Comment by kkemple** [comment]
It is currently only stripping /** style comments for multiline, not /* style

This will be fixed by tonight, adding support for /* */ style comments, just writing some tests. This repo has had some major entropy due to my negligence but I finally have time to get it back up to a really solid place.

**Comment by kkemple** [comment]
resolved
